### ISSUE TITLE
Bacon Hording

### ISSUE THREAD

**Issue by silent1mezzo** [silent1mezzo/jeeves-framework#15]
Unfortunately Jeeves can't deliver bacon to a given user...

Discovered by @jwpeddle
# Doesn't work

Jeeves: deliver_bacon('username')

**Comment by jwpeddle** [comment]
I was quite disappointed, to say the least.

**Comment by silent1mezzo** [comment]
Unfortunately Jeeves has become too reliant on bacon. He won't be able to deliver any in the near future.
