### ISSUE TITLE
Autoreload plugins upon change

### ISSUE THREAD

**Issue by syphernl** [silent1mezzo/jeeves-framework#34]
Would it be possible to auto-reload the plugin whenever it changes? This should make it a lot easier to develop without having to constantly connect/disconnect.

**Comment by silent1mezzo** [comment]
I'm not sure of an efficient way to monitor whether or not a plugin has changed or not, if you have any suggestions I'd love to hear it.

Would having a reload command work? Off the top of my head something like `jeeves reload` that reloads all of the plugins. Would this work?

**Comment by syphernl** [comment]
It could be as "simple" as monitoring the lastmod of the file. 
Manually reloading would also be fine, but automatically is a tad easier.

**Comment by silent1mezzo** [comment]
I can do both where it'll poll Last modified timestamps every X minutes and had a reload plugin as well.

**Comment by syphernl** [comment]
Sounds good to me :)
