### ISSUE TITLE
Bot name should not be hardcoded

### ISSUE THREAD

**Issue by syphernl** [silent1mezzo/jeeves-framework#36]
The admin plugin appears to have the name Jeeves hardcoded.

**Comment by silent1mezzo** [comment]
You're correct. Getting the nickname from settings is fairly easy. If you're able to submit a Pull Request I'll gladly accept it. Otherwise I'll get to this for the next release.

**Comment by silent1mezzo** [comment]
This is now in master. Will be in 0.4.1
